unpack: true
requires:
- category: "distro"
  name: "seed"
  version: ">=0.1"
steps:
- sh build.sh
includes:
- /bin$|/bin/.*
- /dev$|/dev/.*
- /etc$
# We need to skip hostname, hosts and resolv.conf
# Explictly listing what we want from etc
- /etc/X11.*
- /etc/default.*
- /etc/insserv.conf.dmime.types.*
- /etc/python3.*
- /etc/shells.*
- /etc/adduser.conf.*
- /etc/deluser.conf.*
- /etc/iproute2.*
- /etc/mke2fs.confpython3.7.*
- /etc/skel.*
- /etc/alternatives.*
- /etc/dhcp.*
- /etc/issue.*
- /etc/modprobe.d.*
- /etc/rc.local.*
- /etc/ssh.*
- /etc/apache2.*
- /etc/dhcpcd.conf.*
- /etc/issue.net.*
- /etc/modules.*
- /etc/rc0.d.*
- /etc/ssl.*
- /etc/apparmor.d.*
- /etc/dphys-swapfilekernel.*
- /etc/modules-load.drc1.d.*
- /etc/subgid.*
- /etc/apt.*
- /etc/dpkg.*
- /etc/ld.so.cachemotd.*
- /etc/rc2.d.*
- /etc/subuid.*
- /etc/avahi.*
- /etc/environment.*
- /etc/ld.so.conf.*
- /etc/mtab.*
- /etc/rc3.d.*
- /etc/sudoers.*
- /etc/bash.bashrc.*
- /etc/fake-hwclock.datald.so.conf.dnanorc.*
- /etc/rc4.d.*
- /etc/sudoers.d.*
- /etc/bash_completion.*
- /etc/fb.modes.*
- /etc/ld.so.preloadnetconfig.*
- /etc/rc5.d.*
- /etc/sysctl.conf.*
- /etc/bindresvport.blacklistfstab.*
- /etc/ldap.*
- /etc/network.*
- /etc/rc6.d.*
- /etc/sysctl.d.*
- /etc/binfmt.d.*
- /etc/gai.conf.*
- /etc/libaudit.confnetworks.*
- /etc/rcS.d.*
- /etc/systemd.*
- /etc/bluetooth.*
- /etc/gdb.*
- /etc/libnl-3.*
- /etc/nsswitch.confrequest-key.confterminfo.*
- /etc/ca-certificates.*
- /etc/groff.*
- /etc/lighttpd.*
- /etc/opt.*
- /etc/request-key.dtimezone.*
- /etc/ca-certificates.confgroup.*
- /etc/locale.aliasos-release.*
- /etc/resolv.conf.*
- /etc/tmpfiles.d.*
- /etc/calendar.*
- /etc/gshadow.*
- /etc/locale.gen.*
- /etc/pam.conf.*
- /etc/resolvconf.*
- /etc/triggerhappy.*
- /etc/cifs-utils.*
- /etc/gss.*
- /etc/localtime.*
- /etc/pam.d.*
- /etc/resolvconf.confucf.conf.*
- /etc/console-setup.*
- /etc/host.conf.*
- /etc/logcheck.*
- /etc/passwd.*
- /etc/rmt.*
- /etc/udev.*
- /etc/cron.d.*
- /etc/hostname.*
- /etc/login.defs.*
- /etc/paxctld.confrpc.*
- /etc/ufw.*
- /etc/cron.daily.*
- /etc/hosts.*
- /etc/logrotate.confperl.*
- /etc/rpi-issue.*
- /etc/update-motd.d.*
- /etc/cron.hourly.*
- /etc/hosts.allow.*
- /etc/logrotate.dpolkit-1.*
- /etc/rsyslog.conf.*
- /etc/usb_modeswitch.conf.*
- /etc/cron.monthly.*
- /etc/hosts.deny.*
- /etc/machine-id.*
- /etc/ppp.*
- /etc/rsyslog.d.*
- /etc/usb_modeswitch.d.*
- /etc/cron.weekly.*
- /etc/idmapd.conf.*
- /etc/magic.*
- /etc/profile.*
- /etc/securetty.*
- /etc/vim.*
- /etc/crontab.*
- /etc/ifplugd.*
- /etc/magic.mime.*
- /etc/profile.d.*
- /etc/security.*
- /etc/wgetrc.*
- /etc/dbus-1.*
- /etc/init.*
- /etc/mailcap.*
- /etc/protocols.*
- /etc/selinux.*
- /etc/wpa_supplicant.*
- /etc/debconf.conf.*
- /etc/init.d.*
- /etc/mailcap.orderpython.*
- /etc/services.*
- /etc/xattr.conf.*
- /etc/debian_version.*
- /etc/inputrc.*
- /etc/manpath.configpython2.7.*
- /etc/shadow.*
- /etc/xdg.*

- /home$|/home/.*
- /lib$|/lib.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /usr$|/usr/.*
- /var$|/var/.*
