image: golang
prelude:
- apt-get update
- apt-get install git
- git clone https://github.com/mudler/luet
steps:
- cd luet && git checkout develop && make build && mv luet /usr/bin/luet
includes:
- /usr/bin/luet
