unpack: true
includes:
- /bin$|/bin/.*

- /dev$|/dev/.*
- /etc$
# We need to skip hostname \ hosts and resolv.conf (so the package can be also consumed in containers)
# For such setup prefer finalizer steps
# Explictly listing what we want from etc
# Get it with: xzcat stage3-raspi3-1.4-release-std-2020-01-03.tar.xz | tar -t | grep /etc/
- /etc$|/etc/.*

- /home$|/home/.*
- /lib$|/lib.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /usr$|/usr/.*
- /var$|/var/.*
steps:
- equo up
- > 
  ACCEPT_LICENSE=* equo i @wireless 
  @fluxbox 
  app-misc/calamares-sabayon 
  app-text/pastebunz 
  lxde-base/lxdm 
  media-gfx/feh 
  net-dialup/ppp 
  net-dialup/rp-pppoe 
  net-irc/irssi 
  net-misc/tightvnc 
  sys-apps/usbutils 
  sys-block/parted 
  sys-boot/os-prober 
  sys-power/cpupower 
  sys-process/htop 
  www-client/midori 
  x11-themes/adwaita-icon-theme 
  x11-themes/sabayon-artwork-core 
  x11-themes/sabayon-artwork-grub  
  @X 
  app-arch/unrar 
  app-misc/sabayon-live 
  app-misc/sabayon-skel 
  media-fonts/dejavu 
  media-fonts/corefonts 
  media-libs/libtxc_dxtn 
  media-libs/mesa 
  sys-apps/lsb-release 
  sys-apps/usb_modeswitch 
  sys-apps/which 
  sys-process/htop 
  x11-apps/xhost 
  x11-apps/setxkbmap 
  x11-themes/equinox-themes 
  x11-themes/gtk-engines:2 
  x11-themes/hicolor-icon-theme 
  x11-themes/iottinka-artwork 
  x11-terms/xterm 
  x11-libs/libXxf86misc 
- equo cleanup
requires:
- category: "distro"
  name: "sabayon"
  version: "0.1"
