unpack: true
includes:
- /bin$|/bin/.*
- /etc$|/etc/.*
- /home$|/home/.*
- /lib$|/lib/.*
- /media$|/media/.*
- /mnt$|/mnt/.*
- /opt$|/opt/.*
- /root$|/root/.*
- /run$|/run/.*
- /sbin$|/sbin/.*
- /srv$|/srv/.*
- /tmp$|/tmp/.*  
- /usr$|/usr/.*
- /var$|/var/.*
requires:
- category: "distro"
  name: "alpine"
  version: "3.11.3"
