unpack: true
requires:
- category: "distro"
  name: "seed"
  version: ">=0.1"
prelude:
- apk --no-cache add ca-certificates tar gzip wget xz rsync git
- git clone https://github.com/ivandavidov/minimal.git
- cd minimal && git checkout e4ab26d8ee2e9e2e24d47852474d453b19cb0ced
steps:
- mkdir /boot
- rsync -A -a --delete --numeric-ids --recursive -d -H --one-file-system --xattrs minimal/src/minimal_boot/*  --exclude '/etc/resolv.conf'  --exclude '/etc/hostname'  --exclude '/sys/' --exclude '/etc/hosts'  --exclude '/sys/*' --exclude '/proc/*' --exclude '/dev/pts/*'  /boot/
includes:
- /boot$|/boot/.*