unpack: true
requires:
- category: "distro"
  name: "seed"
  version: ">=0.1"
prelude:
- apk --no-cache add ca-certificates tar gzip wget xz rsync git
- git clone https://github.com/ivandavidov/minimal.git
- cd minimal && git checkout e4ab26d8ee2e9e2e24d47852474d453b19cb0ced
prelude:
- rm -rf /boot || true
steps:
- mkdir /boot
- cp minimal/src/minimal_boot /boot
# Needed during ISOIMAGE creation
- cp -rfv /boot/bios/.* /
- cp -rfv /boot/uefi/loader /
includes:
- /boot$|/boot/.*
# Needed ISOIMAGE
- /EFI$|/EFI/.*
- /loader$|/loader/.*

