prelude:
- wget http://kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.xz
- mkdir -p /syslinux
- tar -xvf syslinux-6.03.tar.xz -C /syslinux
steps:
- mkdir -p /boot/syslinux
- mv /syslinux/syslinux-6.03/bios/core/isolinux.bin /boot/syslinux
- mv /syslinux/syslinux-6.03/bios/com32/elflink/ldlinux/ldlinux.c32 /boot/syslinux
- mv /syslinux/syslinux-6.03/bios/mbr/isohdpfx.bin /boot/syslinux
includes:
- /boot$|/boot/.*
requires:
- category: "distro"
  name: "seed"
  version: "0.1"
